[#p4,reftext=P.4]
=== (P.4) Tasks and deliverables

ifdef::env-draft[]
TIP: _**This is the core of the Project book**. It details the individual tasks listed under <<p3>> and their expected outcomes. It define the project's main activities and the results they must produce, associated with the milestone dates defined in <<p3>>._  <<BM22>>
endif::[]

Iteration #1: Weeks 1-4::
- Task 1: Learn required knowledge for project development such as Natural Processing Techniques and its corresponding libraries.
- Task 2: Initial setup and install required tools.

Iteration #2: Weeks 5-8::
- Task 3: Use the Pathological Gambling Project as reference for initial prototype. 
- Task 4: Develop version 1 (functional prototype) for proof of concept.

Iteration #3: Weeks 9-12::
- Task 5: Split into 3 teams and focus on the three different models for the three different types of early risk detection.
- Task 6: Analyze results of the three tasks and focus on potential improvements.

Iteration #4: Weeks 13-16::
- Task 7: Develop version 2 (final product) and test for accuracy.