[#p6,reftext=P.6]
=== (P.6) Risk and mitigation analysis

ifdef::env-draft[]
TIP: _Potential obstacles to meeting the schedule of <<p4>>, and measures for adapting the plan if they do arise. It is essential to be on the lookout for events that could derail the project, and devise mitigation strategies. It can include a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for the project._  <<BM22>>
endif::[]

NLP Learning Curve:: When the original description for the project was released to our group, it was clearly stated that this project would not require any prior experience with AI work, and would instead be a gradual learning process with a ramp up period. To help mitigate the risk of team members falling behind schedule, regular progress status check-ins in our team meetings could help mitigate difficulty. Solutions to help out teammates could come from other members of the group sharing their understanding, or which resources they used if they ran into similar problems. If team member support isn't sufficient, it is recommended for team members to reach out to project facilitators such as Dr. Mosser if further clarification is required.

Difficulty regarding eRisk Specification:: Due to the ambiguity of the project specification in the early states, team members may feel overwhelmed with attempting to stay ahead of the curve in terms of preparing elements of the project before details regarding this year's competition are revealed. Team members are encouraged to keep up to date on all released eRisk specifications and familiarize oneself with the provided past documentation and specification from the prior teams. Additionally, risk mitigation can be attained by team members practising the exercises provided by Dr. Mosser and Dr. Meurs. 

Difficulty Balancing Project Deliverables and Competition Deliverables:: Due to this project having two independent timelines, one for the course deliverables and one for the contest deliverables, team members may experience difficulty balancing both responsibilities. The best way to manage this is to stick to clearly defined schedules and have fair divisions of work in order to ensure that all important project aspects are assigned to someone at all times.
