[#g1,reftext=G.1]
=== (G.1) Context and Overall Objectives

ifdef::env-draft[]
TIP: _High-level view of the project: organizational context and reason for building a system. It explains why the project is needed, recalls the business context, and presents the general business objectives._  <<BM22>>
endif::[]

As society advances so does the integration of technology into our lives. Many people struggle with mental health issues that go unnoticed, and undiagnosed as well, and are isolated so they never get the diagnosis and the support they need. In response to those two points working in tandem, Dr.Mosser’s past teams, along with support from UQAM and several psychologists from around the world, have developed methods and approaches to assist psychiatrists with diagnosing mental health issues. Our goal for this project is to enter a competition hosted by eRisk where we will develop a Natural Language Processing (NLP) architecture that will be used to aid health care providers in early risk detection of certain mental health issues and conditions from data collected over the internet. The internet and social media posting can be the cause of many negative mental health symptoms, but, with the amount of data available, we think we can use it to our advantage to help diagnose and detect these issues. We will be basing our NLP system off of the current works and methods developed over the past years by eRisk. This will be done in collaboration with Professor Mosser and individuals from the University of Montreal. There are a wide variety of use cases we may be working on, but, as of right now, the main information we know is that we will be given a mental health issue or situation where we will be required to make a NLP system in order to take data we are given and determine the risk of said mental health issue for the given user. Our goal is to help eRisk expand the number of use cases that their NLP systems are applicable for and cover a wider range of scenarios and personal profiles. They have a strong base of NLP systems and data to work with, but the greater the breadth of the research the more people it can help. Early intervention is very important for mental health issues, and for issues such as suicidal tendencies and online predatory tendencies, it can be a matter of life and death. That is why this work is so important, and we will be working on expanding the number of situations in which it will be able to help people.

