[#g1,reftext=G.1]
=== (G.1) Context and Overall Objectives

ifdef::env-draft[]
TIP: _High-level view of the project: organizational context and reason for building a system. It explains why the project is needed, recalls the business context, and presents the general business objectives._  <<BM22>>
endif::[]

Many people with mental health issues do not receive treatment, this can be due to a number of different barriers: lack of financial means, low energy and motivation, no available mental health professionals in an area, and a great many more. Many people with mental health issues, both those receiving treatment and those who are not, use social media as a way to vent and connect with others over their shared struggles. This social media use represents a body of information that could be used to more efficiently diagnose patients and improve psychologist workloads, in turn helping lessen barriers around seeking treatment.

Utilizing this information effectively requires systems that can process a large amount of data, much of it irrelevant to issue's of mental health, and provide predictions for specific disorders or direct a psychologist towards certain online interactions that may be relevant. This implies the usage of machine learning techniques, and specifically natural language processing techniques, to analyze all this data quickly. The objective of this project is to explore the applications of machine learning to this area of mental health identification.

In order to do this the project will need labelled data to develop models on. This is not easy to find, attempting to collect this ourselves would involve many consent and privacy concerns and be both difficult and time consuming. In order to have easy access to already developed data the team will be joining the "early risk prediction on the internet" competition, or eRisk for short. ERisk is a competition that presents a number of tasks relating to predicting mental health indicators from individuals' online post history with the goal of encouraging research into this area. The competition provides labelled data that models can be trained on as well as a structured environment through which the system developed for this project can be compared to other entries. This provides a golden opportunity for the team to meet their objectives and as such this project will largely be structured around this competition.

