[#g2,reftext=G.2]
=== (G.2) Current situation

ifdef::env-draft[]
TIP: _Current state of processes to be addressed by the project and the resulting system. It describes the current situation, upon which the system is expected to improve_  <<BM22>>
endif::[]

Currently, it can be a very difficult task to diagnose people with mental health conditions. If you are suffering from a mental health condition, it can often be hard to even originally reach out for help, and it is easy to feel isolated and alone. Due to this, many people never reach out to anyone and suffer alone especially in this post pandemic world where people still often feel very isolated as a hangover effect of the pandemic isolation. That is why it is so important to be able to identify the people who need help and offer them said help.

Currently there is no good system that will help you identify potential early warning signs of mental health issues based on a person’s online posting history. eRisk has been working on developing an interdisciplinary research field that aims to be applicable to a wide range of situations and to many different personal profiles. These can be used to help identify potential online predators, people with suicidal inclinations, or people that are susceptible to depression.

eRisk has been running since 2017 and has grown from having just one proposed task to now having three each year. Each year the competition releases labelled training data for each task in late December, the teams then have until April to develop their models before they run them on unlabelled test data eRisk releases. The results the models produce on this test data are submitted to the competition for evaluation and results are released in May. Each task is built around predicting mental health indicators from online posts but each explores a different facet of this process. The tasks for this year are as follows:

- **Task 1: Search for Symptoms of Depression** This task explores ranking sentences by relevance to a mental health issue so the most important information from a large body of data can be identified.
- **Task 2: Early Detection of Signs of Anorexia** This task explores detecting mental health issues quickly. It simulates monitoring an individual's posting activity in real time and encourages participants to come to an accurate conclusion in as few posts as possible.
- **Task 3: Measuring the Severity of the Signs of Eating Disorders** This task explores directly predicting the severity of different mental health symptoms from an individual's posting activity.

All three of these tasks have been run in two prior years of eRisk already. The first years for each task no labelled training data was provided; the second years the test data from the first year, now with labels, was provided as training data; and the third year, this year, the test data from the first and second years was labelled and provided as training data.

