[#g2,reftext=G.2]
=== (G.2) Current situation

ifdef::env-draft[]
TIP: _Current state of processes to be addressed by the project and the resulting system. It describes the current situation, upon which the system is expected to improve_  <<BM22>>
endif::[]

Currently, it can be a very difficult task to diagnose people with mental health conditions. If you are suffering from a mental health condition, it can often be hard to even originally reach out for help, and it is easy to feel isolated and alone. Due to this, many people never reach out to anyone and suffer alone especially in this post pandemic world where people still often feel very isolated as a hangover effect of the pandemic isolation. That is why it is so important to be able to identify the people who need help and offer them said help. Currently there is no good system that will help you identify potential early warning signs of mental health issues based on a person's online posting history. eRisk has been working on developing an interdisciplinary research field that aims to be applicable to a wide range of situations and to many different personal profiles. Previous years competitions have varying tasks such as "Measuring the severity of the signs of Eating Disorders" which attempt to predict as the name implies the severity of eating disorders for a given individual. These tasks can be used to help identify potential online predators, people with suicidal inclinations, or people that are susceptible to depression. They are building their reach through research and NLP, but it is still in the early stages and is limited. What we will do is tackle a new mental health problem that they have yet to consider and build on their previous practices and improve it making it relevant for our mental health issue. The goal is all about expanding the use cases that this methodology and research is applicable for and that is what we will be providing. 
