[#g2,reftext=G.2]
=== (G.2) Current situation

ifdef::env-draft[]
TIP: _Current state of processes to be addressed by the project and the resulting system. It describes the current situation, upon which the system is expected to improve_  <<BM22>>
endif::[]

There are currently no tools currently existing that utilize machine learning and online posting history to make predictions about mental health issues. This area of research is quite new and exploration is still ongoing, hence why competitions like eRisk exist.

eRisk has been running since 2017 and has grown from having just one proposed task to now having three each year. Each year the competition releases labelled training data for each task in late December, the teams then have until April to develop their models before they run them on unlabelled test data eRisk releases. The results the models produce on this test data are submitted to the competition for evaluation and results are released in May. Each task is built around predicting mental health indicators from online posts but each explores a different facet of this process. The tasks for this year are as follows:

- **Task 1: Search for Symptoms of Depression** This task explores ranking sentences by relevance to a mental health issue so the most important information from a large body of data can be identified.
- **Task 2: Early Detection of Signs of Anorexia** This task explores detecting mental health issues quickly. It simulates monitoring an individual's posting activity in real time and encourages participants to come to an accurate conclusion in as few posts as possible.
- **Task 3: Measuring the Severity of the Signs of Eating Disorders** This task explores directly predicting the severity of different mental health symptoms from an individual's posting activity.

All three of these tasks have been run in two prior years of eRisk already. The first years for each task no labelled training data was provided; the second years the test data from the first year, now with labels, was provided as training data; and the third year, this year, the test data from the first and second years was labelled and provided as training data.

