[#g3,reftext=G.3]
=== (G.3) Expected Benefits

ifdef::env-draft[]
TIP: _New processes, or improvement to existing processes, made possible by the project’s results. It presents the business benefits expected from the successful execution of the project. **This chapter is the core of the Goals book**, describing what the organization expects from the system. It ensures that the project remains focused: if at some stage it gets pushed in different directions, with “creeping featurism” threatening its integrity, a reminder about the original business goals stated in those chapters will help._  <<BM22>>
endif::[]

The implementation of a natural language processing model that can detect early signs of mental health issues will have multiple benefits to its stakeholders. The system when completed will be used to participate in the 2024 eRisk competition. eRisk is an organization whos goal is to research early risk detection on the internet (in the case of this system and competition, the project focuses primarily on mental health). By participating in this competition, the system aims to benefit eRisk and its participants by providing any information that could possibly provide useful for furthering this research topic.

The system will be used to process data taken from an individuals messages (In the case of past competitions, the messages are normally taken from "reddit" users in communities that are related to the topic (Ex: r/ProblemGambling for detecting early signs of pathological gambling)). The system intends to benefit individuals who are affected by mental health issues by detecting early signs of these issues before they lead to a point that is irrecoverable for the individual.

.Goal Model for {project-title}
image::models/goals.svg[scale=50%,align="center"]
