[#g4,reftext=G.4]
=== (G.4) Functionality overview

ifdef::env-draft[]
TIP: _Overview of the functions (behavior) of the system. Principal properties only (details are in the System book). It is a short overview of the functions of the future system, a kind of capsule version of book S, skipping details but enabling readers to get a quick grasp of what the system will do._  <<BM22>>
endif::[]

The requirements listed represent the core functionality of the Natural Language Processing system used to detect early signs of mental health issues. Detailed descriptions are available in the system section of this document.

**Functional Requirements**

- **Detecting Signs of Depression:** The system will be able to rank a set of written sentences based on how related they are to various symptoms of depression.
- **Early Detection of Anorexia:** The system will be able to predict whether an individual shows signs of anorexia based on their online posting history. The system will aim to do this quickly, in other words, with as few posts as possible.
- **Detecting Signs of Eating Disorders**: The system will be able to fill out a copy of the Eating Disorder Examination Questionnaire (the EDE-Q) for an individual based on their online posting history.

**Non-Functional Requirements**

- **Security of Data**: The system should maintain privacy standards and not leak confidential information (see section E.3 "Data Privacy Regulations" for more information).

