[#g4,reftext=G.4]
=== (G.4) Functionality overview

ifdef::env-draft[]
TIP: _Overview of the functions (behavior) of the system. Principal properties only (details are in the System book). It is a short overview of the functions of the future system, a kind of capsule version of book S, skipping details but enabling readers to get a quick grasp of what the system will do._  <<BM22>>
endif::[]

The requirements listed represent the core functionality of the Natural Language Processing system used to detect early signs of mental health issues. Detailed descriptions are available in the system section of this document.

**Functional Requirements**

The functionality of the system is built around each of eRisk's three tasks for the year:

- **Detecting Signs of Depression:** The system will be able to rank a set of written sentences based on how related they are to the 21 symptoms of depression laid out in the Beck Depression Inventory (the BDI) <<BDI>>. The system should produce a separate ranking for each of the 21 symptoms.
- **Early Detection of Anorexia:** The system will be able to predict whether an individual shows signs of anorexia based on their online posting history. The system will do this post by post, like it is monitoring an individuals online activity in real-time, and will attempt to make the prediction as quickly as possible.
- **Detecting Signs of Eating Disorders**: The system will be able to fill 22 of the 28 questions on the Eating Disorder Examination Questionnaire (the EDE-Q, for an overview see: https://www.corc.uk.net/outcome-experience-measures/eating-disorder-examination-questionnaire-ede-q/) <<EDEQ1>><<EDEQ2>> for an individual based on their online posting history. The six questions that were left out of the questionnaire, questions 13 to 18, do not follow the same answer format as the rest of the questions, a 0 to 6 rating of severity, and ask for an arbitrary number instead. These questions were likely omitted to make the task more focused.

**Non-Functional Requirements**

- **Security of Data**: The system should maintain privacy standards and not leak confidential information (see section E.3 "Data Privacy Regulations" for more information).

