[#g6,reftext=G.6]
=== (G.6) Limitations and Exclusions

ifdef::env-draft[]
TIP: _Aspects that the system need not address. It states what the system will not do. This chapter addresses a key quality attribute of good requirements: the requirements must be delimited (or “scoped”). <<g6>> is not, however, the place for an analysis of risks and obstacles, which pertain to the project rather than the goals and correspondingly appears in chapter <<p6>>._  <<BM22>>
endif::[]

- The system need not address the acquisition of an individual's post history from external sites. The focus of the system is on developing and optimizing prediction models, implementing functionality to connect to a site and retrieve an individuals post history is outside the scope of this project and left for future development.

- The system need not provide an interface that psychologists can use in their everyday practice. Like above, the focus of the system is on developing prediction models, implementing these models into software that psychologists with limited technical knowledge can use is outside the scope of this project.

