[#s1,reftext=S.1]
=== (S.1) Components

ifdef::env-draft[]
TIP: _Overall structure expressed by the list of major software and, if applicable, hardware parts._  <<BM22>>
endif::[]

- **Text Pre-Processing Component**: Text is processed with the following methods: Tokenization, Lowercasing, Stopword Removal, and Stemming or Lemmatization. This turns the texts into a format that reduces the potential for noise to cause false positive or false negative answers.
- **Vectorization Component**: Converting words/tokens into numerical vectors. This turns the texts into a format that can be understood by text based natural language processing models.
- **Prediction Component**: Generate a prediction on wether there are early signs of mental health issues present in the text. The prediction will be generated using a natural language processing model that is suited for the specific task.
- **Output Component**: Due to a lack of a need for usability as well as due to restriction placed by the eRisk competition, the output will be sent to a file in the format specified by the eRisk organizers.
