[#s2,reftext=S.2]
=== (S.2) Functionality

ifdef::env-draft[]
TIP: _**This is the bulk of the System book, describing elements of functionality (behaviors)**. This chapter corresponds to the traditional view of requirements as defining "**what the system does**”. It is organized as one section, S.2.n, for each of the components identified in <<s1>>, describing the corresponding behaviors (functional and non-functional properties)._  <<BM22>>
endif::[]

This section describes in further detail the components listed in the previous section by describing their functional and non-functional requirements.

**General and Security**

Non-Functional Requirements:

- GR1: The system should be compatible on MacOS, Windows, and Linux.
- GR2: Copyrighted content should not be included in the output without reference.
- SR1: The system will be tested periodically to detect a potential lack of processing power.
- SR2: Sensitive user data must not be present within the results generated.

**Task 1: Search for Symptoms of Depression Component**

Functional Requirements:

- T1FR-1: The system will be able to parse both xml and jsonl files.
- T1FR-2: The system will rank input sentences from users based on their correlation to 21 depression symptoms from the beck depression index.
- T1FR-3: The system will send the predictions to a txt file in the format "{symptom_number}, Q0, {sentence-id}, {position_in_ranking}, {score}, {system_name}".

**Task 2: Early Detection of Signs of Anorexia Component**

Functional Requirements:

- T2FR-1: The system will be able to parse both xml and jsonl files.
- T2FR-2: The system will make predictions given a set of a user's posts.
- T2FR-3: The system will allow posts to be added to a user's set of posts and the system will update the prediction for that user.
- T2FR-4: The system will send the predictions to a txt file in the format "{username} {prediction (0 or 1)}" with each entry being on a separate line.


**Task 3: Measuring the Severity of the Signs of Eating Disorders Component**

Functional Requirements:

- T3FR-1: The system will be able to parse both xml and jsonl files.
- T3FR-2: The system will make predictions given a set of a user's posts.
- T3FR-3: The system will send the predictions to a txt file in the format "{username} {prediction (0-6) for Q1} ... {prediction (0-6) for Q28}" with each entry being on a separate line.
