[#s4,reftext=S.4]
=== (S.4) Detailed usage scenarios

ifdef::env-draft[]
TIP: _Examples of interaction between the environment (or human users) and the system, expressed as user stories. Such scenarios are not by themselves a substitute for precise descriptions of functionality (<<s3>>), but provide an important complement by specifying cases that these behavior descriptions must support; they also serve as a basis for developing test cases. The scenarios most relevant for stakeholders are given in chapter <<g5>> in the Goals book, at a general level, as use cases; in contrast, <<s4>> can refer to system components and functionality (from other chapters of the System book) as well as special and erroneous cases, and introduce more specific scenarios._  <<BM22>>
endif::[]

==== Use Case 1: Search for symptoms of depression
. User provides a series of sentences.
. Model ranks sentences based on the 21 symptoms of the beck depression index questionaire.

==== Use Case 2: Early detection of signs of anorexia
. User provides an series of posts belonging to a single user.
. Model provides a 0 if the user is predicted to not have anorexia and a 1 if the user is predicted to have anorexia.

==== Use Case 3: Measuring the severity of the signs of eating disorders
. User provides an series of posts belonging to a single user.
. Model provides a 0-6 score predicting the user's answers to the eating disorder examination questionnaire. 

