[#s6,reftext=S.6]
=== (S.6) Verification and acceptance criteria

ifdef::env-draft[]
TIP: _Specification of the conditions under which an implementation will be deemed satisfactory. Here, "verification" as shorthand for what is more explicitly called "Verification & Validation" (V&V), covering several levels of testing — module testing, integration testing, system testing, user acceptance testing — as well as other techniques such as static analysis and, when applicable, program proving._  <<BM22>>
endif::[]

* Data processing functions (pre_process, vectorize) will be deemed satisfactory if their actual output given some test data aligns with the expected output based on the settings they are given. This will be determined through unit tests.
* The data processing pipeline will be deemed satisfactory if, when given some test data, the actual output of each step in the pipeline matches the expected output. This will be determined through a series of unit tests.
* The accuracy measure calculations will be deemed satisfactory if, when given some test data, the resulting accuracy measures match pre-calculated expected values. This will be done through unit tests.
* The model training functions (train_model) will be deemed satisfactory if the model managed to achieve an accuracy on the eRisk training data comparable to a control accuracy (ie. rate of successful diagnoses by mental health professionals, accuracy of a different, comparable model).
* The entire system will be deemed satisfactory if the resulting models manage to achieve an accuracy on the eRisk testing data comparable to a control accuracy (ie. rate of successful diagnoses by mental health professionals, accuracy of a different, comparable model).
