[#e3,reftext=E.3]
=== (E.3) Constraints

ifdef::env-draft[]
TIP: _Obligations and limits imposed on the project and system by the environment. This chapter defines non-negotiable restrictions coming from the environment (business rules, physical laws, engineering decisions), which the development will have to take into account._  <<BM22>>
endif::[]

- *Resource Constraint*: The final NLP models must be able to run on Canada Compute Servers without external processes running in conjunction.

- *Data Regulatory Constraint*: The system must be built to handle and process different sizes of data provided by ERisk and process them while abide by the set of rules that eRisk defined, such as the General Data Protection Regulation (GDPR).

- *Time Constraint*: The system must be built following the schedule of the ERisk's important dates, such as releasing training data and deployment on servers.

- *Compatibility* The system must follow ERisk's specification during deployment and testing phases in order to qualify for the program.


