[#e4,reftext=E.4]
=== (E.4) Assumptions

ifdef::env-draft[]
TIP: _Properties of the environment that may be assumed, with the goal of facilitating the project and simplifying the system. It defines properties that are not imposed by the environment (like those in <<e3>>) but assumed to hold, as an explicit decision meant to facilitate the system's construction._  <<BM22>>
endif::[]


- *Availability of ERisk Servers*: It is assumed that ERisk testing and deployment servers are active and available at all times during the testing and deployment phase.

- *Accuracy of User Profiles*: The assumption is made that all profile data provided for testing are formatted correctly and will be able to be processed without any errors, disruptions or further development procedures beyond the scope.

- *Distruption of ERisk's Schedule*: It is assumed that ERisk's schedule, including the date and time provided for important dates, are executed on time and in sync with the development process.

- *Connection Stability*: It is assumed that the connection between the system and ERisk labs' servers are smooth and stable, without connectivity disruptions from internet service providers.

- *Consistent Development Platforms*: The assumption is made that documentation and utilization will be consistent throughout the development process without sudden changes in stakeholders or business plans.
